services:
  backend:
    build:
      context: ./backend/backend
      dockerfile: Dockerfile
    container_name: roma_events_backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    command:
      - "--spring.datasource.url=jdbc:postgresql://postgres:5432/roma_events"
      - "--spring.datasource.username=postgres"
      - "--spring.datasource.password=postgres"
      - "--server.port=8081"

  postgres:
    image: postgres:15
    container_name: roma_events_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: roma_events
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: roma_events_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@romaevents.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_DISABLE_POSTFIX: "1"
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "8080:5050"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:

  