INSERT INTO categories (name, description) VALUES
('Ambiente', 'Eventi e iniziative legati ad ambiente, sostenibilità e verde urbano'),
('Casa', 'Eventi e iniziative legati alla casa e alle politiche abitative'),
('Commercio Impresa', 'Eventi e iniziative su commercio, attività produttive e impresa'),
('Commissione Pari Opportunità', 'Eventi e iniziative della Commissione Pari Opportunità'),
('Cultura', 'Eventi culturali, mostre, spettacoli, rassegne e attività artistiche'),
('Diritti', 'Eventi e iniziative sui diritti e la cittadinanza'),
('Disabilità', 'Eventi e iniziative dedicate a inclusione e disabilità'),
('Formazione e Lavoro', 'Eventi e iniziative su formazione, orientamento e lavoro'),
('Innovazione e Smart City', 'Eventi e iniziative su innovazione, digitale e smart city'),
('Luoghi degli Eventi', 'Tematica usata dal portale per eventi associati a luoghi specifici'),
('Luoghi delle Notizie', 'Tematica usata dal portale per contenuti legati a luoghi'),
('Mobilità e Trasporti', 'Eventi e iniziative su mobilità, viabilità e trasporti'),
('Pari opportunità', 'Eventi e iniziative sulle pari opportunità'),
('Patrimonio', 'Eventi e iniziative sul patrimonio pubblico e culturale'),
('Presidenza Assemblea Capitolina', 'Eventi e iniziative della Presidenza dell''Assemblea Capitolina'),
('Protezione Civile', 'Eventi e iniziative di protezione civile'),
('Roma', 'Eventi e iniziative istituzionali o generali sulla città di Roma'),
('Scuola', 'Eventi e iniziative per scuola, studenti e comunità educante'),
('Sicurezza Urbana', 'Eventi e iniziative sulla sicurezza urbana'),
('Sindaco', 'Eventi e iniziative collegate all''attività del Sindaco'),
('Sociale', 'Eventi e iniziative in ambito sociale'),
('Sport', 'Eventi e iniziative sportive'),
('Turismo', 'Eventi e iniziative in ambito turistico'),
('Urbanistica', 'Eventi e iniziative su urbanistica e trasformazione del territorio')
ON CONFLICT DO NOTHING;