spring.application.name=backend

server.port=${PORT:8081}
server.address=0.0.0.0

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/roma_events}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

openweather.api.key=${OPENWEATHER_API_KEY}
openrouteservice.api.key=${OPENROUTESERVICE_API_KEY}
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

properties.server.error.include-message=always