spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/roma_events
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
openweather.api.key=f08ab4f33631a63bd48c9a5d7bc4c6d5

jwt.secret=RomaEventsJwtSecretKey2026MoltoLungaESicuraPerHS256
jwt.expiration-ms=86400000

server.port=8081